server:
  port: 8080

spring:
  application:
    name: ops-portal
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

# Health check endpoints configuration
health:
  endpoints:
    - name: "App1"
      url: "https://www.rvybot.com/health"
      timeout: 5000
    - name: "App2"
      url: "https://www.rvybot.com/health"
      timeout: 3000
    - name: "App3"
      url: "https://www.rvybot.com/health"
      timeout: 3000

# SSH Configuration for Linux servers
ssh:
  default-timeout: 30000
  servers:
    - name: "prod-server-1"
      host: "192.168.1.100"
      port: 22
      username: "admin"
      key-path: "/path/to/private/key"
    - name: "prod-server-2"
      host: "192.168.1.101"
      port: 22
      username: "admin"
      key-path: "/path/to/private/key"



# Windows VM Configuration
windows:
  servers:
    - name: "win-vm-1"
      host: "192.168.1.200"
      username: "administrator"
      domain: "WORKGROUP"
    - name: "win-vm-2"
      host: "192.168.1.201"
      username: "administrator"
      domain: "WORKGROUP"

# Git Configuration for config files
git:
  repositories:
    - name: "config-repo"
      url: "https://github.com/your-org/config-repo.git"
      local-path: "/tmp/config-repo"
      branches:
        - "main"
        - "develop"
        - "staging" 